---
# Add tasks to update and upgrade the system here
# Add tasks to install packages such as python3 and nginx here
# Use a defaults/main.yml file to define package names and/or versions if necessary
# Use a handlers/main.yml file to enable and start nginx

- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Install python3 and python3-venv
  apt:
    name: 
      - python3
      - python3-venv
    state: present

- name: Ensure nginx is installed
  apt:
    name: nginx
    state: present
  notify: enable nginx


- name: Update and upgrade the system
  apt:
    update_cache: yes
    upgrade: dist
  become: yes


- name: Install Python3 virtualenv package
  apt:
    name: python3-venv
    state: present
  become: yes
